; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:wemos_d1_mini32]
platform = espressif32
board = wemos_d1_mini32
framework = arduino

monitor_speed = 115200

#upload_protocol = espota
#upload_port = 192.168.1.54

build_flags =
    #to są zmienne środowiskowe które ustawia się w systemie Windows jako zmienne użytkownika
    #dzięki temu wrażliwe dane nie są dostępne w repozytorium
    -D WIFI_SSID=\"${sysenv.WIFI_SSID_HOME-EXT2}\"
    -D WIFI_PASS=\"${sysenv.WIFI_PASSWORD_ORANGE}\"
    -D MQTT_SERVER=\"${sysenv.MQTT_IP}\"
    -D MQTT_USER=\"${sysenv.MQTT_USER}\"
    -D MQTT_PASS=\"${sysenv.MQTT_PASSWORD}\"


lib_deps =
    knolleary/PubSubClient @ 2.8