; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:wemos_d1_mini32]
platform = espressif32
board = wemos_d1_mini32
framework = arduino

monitor_port = socket://192.168.1.41:23
monitor_speed = 115200

upload_protocol = espota
upload_port = 192.168.1.41

lib_deps =
    knolleary/PubSubClient @ 2.8
    jandrassy/TelnetStream

build_flags =
    #To pozwala na nadpisanie Terminal przez wifi i działa tak że nadpisuje funkcje Serial
    #dzięki temu można korzystać z TelnetStream zamiast Serial, a dane będą wysyłane przez WiFi do komputera
    #potrzebny jest do tego plik serial_telnet_override.h, który znajduje się w folderze include, oraz plik serial_telnet_override.cpp, który znajduje się w folderze src
    -include include/serial_telnet_override.h

    #to są zmienne środowiskowe które ustawia się w systemie Windows jako zmienne użytkownika
    #dzięki temu wrażliwe dane nie są dostępne w repozytorium
    -D WIFI_SSID=\"${sysenv.WIFI_SSID_HOME-EXT2}\"
    -D WIFI_PASS=\"${sysenv.WIFI_PASSWORD_ORANGE}\"
    -D MQTT_SERVER=\"${sysenv.MQTT_IP}\"
    -D MQTT_USER=\"${sysenv.MQTT_USER}\"
    -D MQTT_PASS=\"${sysenv.MQTT_PASSWORD}\"
    -D MQTT_CLIENT_ID=\"Gwintownica-ESP32\"
    -D WIFI_HOSTNAME=\"Gwintownica-ESP32\"


